default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
  - repo: https://github.com/joshuachp/pre-commit-hooks
    rev: v0.4.2
    hooks:
      - id: typos
      - id: committed
      - id: lua-stylua
      - id: lua-check
      - id: sh-check
      - id: sh-fmt
      - id: run-dprint
        types_or: [markdown]
      - id: run-prettier
        types_or: [yaml, json]
        exclude: "^lazy-lock.json$"
