default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
  - repo: https://github.com/joshuachp/pre-commit-hooks
    rev: 0.1.39
    hooks:
      - id: typos
      - id: committed
      - id: lua-stylua
      - id: lua-check
      - id: nix-nixfmt
      - id: nix-statix
      - id: nix-flake-check
