repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
  - repo: https://github.com/joshuachp/pre-commit-hooks
    rev: 0.1.34
    hooks:
      - id: typos
      - id: committed
      - id: lua-stylua
      - id: nix-nixpkgs-fmt
      - id: nix-statix
      - id: nix-flake-check
